git:
  depth: 3
notifications:
  email: false

sudo: required
dist: trusty

language: node_js
node_js:
  - "6"
os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update && sudo apt-get install --no-install-recommends -y gcc-multilib g++-multilib icnsutils rpm graphicsmagick xz-utils libdbus-1-dev libglib2.0-dev ;fi
  - npm install -g node-gyp electron-builder
install:
  - npm install
  - npm run rebuild

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run buildLinux; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run buildOSX; fi

branches:
  only:
    - master